config/routes.rb
Rails.application.routes.draw do
  resources :agendas

end

app/models/agenda.rb
class Agenda < ActiveRecord::Base
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]

  # GET /agendas
  # GET /agendas.json
  def index
    @agendas = Agenda.all
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render :show, status: :created, location: @agenda }
      else
        format.html { render :new }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1
  # PATCH/PUT /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { render :show, status: :ok, location: @agenda }
      else
        format.html { render :edit }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda.destroy
    respond_to do |format|
      format.html { redirect_to agendas_url, notice: 'Agenda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_params
      params.require(:agenda).permit(:nombre, :direccion, :numerotelefono)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/agendas/_form.html.erb
<%= form_for(@agenda) do |f| %>
  <% if @agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% @agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :numerotelefono %><br>
    <%= f.text_field :numerotelefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing Agenda</h1>

<%= render 'form' %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listado de Contactos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Numerotelefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= agenda.nombre %></td>
        <td><%= agenda.direccion %></td>
        <td><%= agenda.numerotelefono %></td>
        <td><%= link_to 'Mostrar', agenda %></td>
        <td><%= link_to 'Editar', edit_agenda_path(agenda) %></td>
        <td><%= link_to 'Borrar', agenda, method: :delete, data: { confirm: 'Estas Seguro del borrado?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo', new_agenda_path %>

app/views/agendas/new.html.erb
<h1>New Agenda</h1>

<%= render 'form' %>

<%= link_to 'Back', agendas_path %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @agenda.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @agenda.direccion %>
</p>

<p>
  <strong>Numerotelefono:</strong>
  <%= @agenda.numerotelefono %>
</p>

<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Oneproyect</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>